In [187]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [188]:
df = pd.read_csv('train_dataset.txt',sep = ';',header = None,names = ['Text','Emotion'])

In [189]:

df.head()

                                                Text  Emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [190]:
df.isnull().sum()

Text       0
Emotion    0
dtype: int64

In [191]:
df['Emotion'].value_counts()

Emotion
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [192]:
df['Emotion'] = df['Emotion'].map({"joy":0,"sadness":1,"anger":2,"fear":3,"love":4,"surprise":5})

In [193]:
df

                                                    Text  Emotion
0                                i didnt feel humiliated        1
1      i can go from feeling so hopeless to so damned...        1
2       im grabbing a minute to post i feel greedy wrong        2
3      i am ever feeling nostalgic about the fireplac...        4
4                                   i am feeling grouchy        2
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        1
15996  i am now turning and i feel pathetic that i am...        1
15997                     i feel strong and good overall        0
15998  i feel like this was such a rude comment and i...        2
15999  i know a lot but i feel so stupid because i ca...        1

[16000 rows x 2 columns]

In [194]:
df['Text'] = df['Text'].apply(lambda x : x.lower())
df['Text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: Text, Length: 16000, dtype: object

In [195]:
#remove punchuation from data
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [196]:
df['Text'] = df['Text'].apply(remove_punc)

In [197]:
#remove number from data 
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['Text'] = df['Text'].apply(remove_numbers)

In [198]:
#remove emojis from data
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['Text'] = df['Text'].apply(remove_emojis)

In [199]:
import nltk

In [200]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [201]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [202]:
stop_words = set(stopwords.words('english'))

In [203]:
df.loc[1]['Text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [204]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [205]:
df['Text'] = df['Text'].apply(remove)

In [206]:
df.loc[1]['Text']

'go feeling hopeless damned hopeful around someone cares awake'

In [207]:
df

                                                    Text  Emotion
0                                  didnt feel humiliated        1
1      go feeling hopeless damned hopeful around some...        1
2              im grabbing minute post feel greedy wrong        2
3      ever feeling nostalgic fireplace know still pr...        4
4                                        feeling grouchy        2
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        1
15996  turning feel pathetic still waiting tables sub...        1
15997                           feel strong good overall        0
15998                     feel like rude comment im glad        2
15999                       know lot feel stupid portray        1

[16000 rows x 2 columns]

In [208]:
df['Emotion'].value_counts()

Emotion
0    5362
1    4666
2    2159
3    1937
4    1304
5     572
Name: count, dtype: int64

In [209]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Text'], df['Emotion'], test_size=0.20, random_state=42)

In [210]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: Text, Length: 12800, dtype: object

In [211]:
X_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
15578    feel useful pulpit find ironic often question ...
5746             dried bladders ready day im feeling brave
6395                             feel thrilled matter days
7624     woke morning text mr c declaring walking work ...
15245                                            feel dumb
Name: Text, Length: 3200, dtype: object

In [212]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Check for Bag_Of_Words

In [213]:
bag_of_word_vectorizer = CountVectorizer()
X_train_bow = bag_of_word_vectorizer.fit_transform(X_train)
X_test_bow = bag_of_word_vectorizer.transform(X_test)

In [214]:
logistic_model = LogisticRegression()
logistic_model.fit(X_train_bow,y_train)

LogisticRegression()

In [215]:
log_pred = logistic_model.predict(X_test_bow)
print(accuracy_score(y_test, log_pred))

0.8896875

# Check For TFIDFVectorizer

In [216]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [217]:
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [218]:
log_pred = logistic_model.predict(X_test_tfidf)
print(accuracy_score(y_test,log_pred ))

0.8628125

In [219]:
import joblib

In [220]:

joblib.dump(logistic_model, "model.pkl")
joblib.dump(tfidf_vectorizer, "vectorizer.pkl")

print(" Model & Vectorizer saved")

 Model & Vectorizer saved